development:
  adapter: postgresql
  encoding: unicode
  database: annotate-life_development
  pool: 5
  username: jmahowald
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: annotate-life_test
  pool: 5
  username: jmahowald
  password:
